import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]
# live_config_reload = true

[window]
opacity = 0.95

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 10

[font.normal]
family = "MesloLGS NF"

# [mouse]
# bindings = [
#   { mouse = "Middle", action = "Paste" }
# ]

# [font.bold]
# # family = "JetBrainsMono Nerd Font"
# # style = "Bold"
# 
# # [font.glyph_offset]
# # x = 0
# # y = 0
# 
# [font.italic]
# family = "JetBrainsMono Nerd Font"
# 
# [font.normal]
# family = "JetBrainsMono Nerd Font"
# style = "Regular"

